"""empty message

Revision ID: fce52dc8c971
Revises: a7a4afe6aeed
Create Date: 2023-04-14 22:19:48.810785

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'fce52dc8c971'
down_revision = 'a7a4afe6aeed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
